config/routes.rb
Contact2::Application.routes.draw do

  resources :contacts
  root :to => 'contacts#index'
  

end

app/models/contact.rb
class Contact < ActiveRecord::Base
  attr_accessible :first_name, :gecond_name, :telephone
 
  self.per_page = 7
  # validates :first_name, :gecond_name, :telephone, :presence => true
 
end

app/controllers/ajax_controller.rb
class AjaxController < ApplicationController
  after_filter :clear_return_to

  def framework
    render
  end
  
  private
  
  # Don't return to the framework path, return to root
  def clear_return_to
    return unless Ajax.is_enabled?
    if session[:return_to] =~ %r[#{Ajax.framework_path}]
      session[:return_to] = session[:return_to].sub(%r[#{Ajax.framework_path}], '/')
      Rails.logger.info("[ajax] return_to / instead of #{Ajax.framework_path}")
    end
  end

  unloadable # needed when installed as a plugin
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  # GET /contacts
  # GET /contacts.json
  def index
    
    @contact = Contact.new
    @contacts = Contact.paginate(:page => params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.js
      format.json { render json: @contacts }
    end
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
    @contact = Contact.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @contact }
    end
  end

  # GET /contacts/new
  # GET /contacts/new.json
  def new
    @contact = Contact.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @contact }
    end
  end

  # GET /contacts/1/edit
  def edit
    @contact = Contact.find(params[:id])
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(params[:contact])

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.js
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.js
      end
    end
  end

  # PUT /contacts/1
  # PUT /contacts/1.json
  def update
    @contact = Contact.find(params[:id])

    respond_to do |format|
      if @contact.update_attributes(params[:contact])
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact = Contact.find(params[:id])
    @contact.destroy

    respond_to do |format|
      format.html { redirect_to contacts_url }
      format.js {}
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/ajax/framework.html.erb
<script type="text/javascript">
  $(function() {
    if (window.ajax !== undefined) {
      window.ajax.loaded_by_framework = true;
    }
  });
</script>

app/views/contacts/_contact.html.erb
<tr class="contact">
	<td><%= contact.first_name %></td>
	<td><%= contact.gecond_name %></td>
	<td><%= contact.telephone %></td>
	<td><%= link_to 'Destroy', contact, method: :delete, remote: true %></td>
</tr>

app/views/contacts/_form.html.erb
<%= form_for(@contact) do |f| %>
  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% @contact.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :gecond_name %><br />
    <%= f.text_field :gecond_name %>
  </div>
  <div class="field">
    <%= f.label :telephone %><br />
    <%= f.text_field :telephone %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contacts/create.js.erb
$(".contact").last().after("<%= escape_javascript(render @contact) %>");
$(":input:not(input[type=submit])").val("");

app/views/contacts/destroy.js.erb
$('.contact').bind('ajax:success', function() {  
        $(this).closest('tr').fadeOut();
}); 

app/views/contacts/edit.html.erb
<h1>Editing contact</h1>

<%= render 'form' %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<h1>Contacts</h1>

<table class="databrouser" border="2">
  
    <tr class="fix_head">
    <td>First name</td>
    <td>Gecond name</td>
    <td>Telephone</td>
  </tr>
  
    <% @contacts.each do |contact| %>
  
    <%= render contact %>
  
    <% end %>
  
  <%= form_for @contact, remote: true, :html=> {:id => 'dd'} do |f| %>
    <tr class="gg">    
           <td>
           <%= f.text_field :first_name, :size => 15 %>
          </td>
          <td>
            <%= f.text_field :gecond_name, :size => 15 %>  
          </td>
          <td>
              <%= f.telephone_field :telephone, :size => 15 %>
          </td>  
          
        </tr>

    <% end %>  

</table>

<br />
<p>
  <%= will_paginate @contacts %>
</p>

app/views/contacts/new.html.erb
<h1>New contact</h1>

<%= render 'form' %>

<%= link_to 'Back', contacts_path %>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>First name:</b>
  <%= @contact.first_name %>
</p>

<p>
  <b>Gecond name:</b>
  <%= @contact.gecond_name %>
</p>

<p>
  <b>Telephone:</b>
  <%= @contact.telephone %>
</p>


<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Contact2</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  
</head>

<body>

<%= yield %>

</body>
</html>